# Generated by Django 4.2.4 on 2023-08-24 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_autor', models.CharField(max_length=200)),
                ('idade_autor', models.IntegerField()),
                ('foto_autor', models.ImageField(upload_to='foto_perfil/')),
            ],
        ),
    ]
