# Generated by Django 4.2.4 on 2023-08-25 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_genero'),
        ('autores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='genero_autor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='livros.genero'),
            preserve_default=False,
        ),
    ]
