# Generated by Django 4.2.4 on 2023-08-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='celular',
            name='ano_celular',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
