# Generated by Django 4.2.4 on 2023-08-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autor', '0002_celular_ano_celular'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_autor', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Celular',
        ),
    ]
