# Generated by Django 4.2.5 on 2023-09-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_tarefa', models.CharField(max_length=200)),
                ('descricao_tarefa', models.TextField()),
                ('status_tarefa', models.BooleanField(default=False)),
            ],
        ),
    ]
