# Generated by Django 4.2.4 on 2023-09-08 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('criadores', '0001_initial'),
        ('tarefas', '0002_alter_tarefa_status_tarefa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarefa',
            options={'verbose_name': 'Tarefassss'},
        ),
        migrations.AddField(
            model_name='tarefa',
            name='responsavel_tarefa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='criadores.criador'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='titulo_tarefa',
            field=models.CharField(max_length=200, verbose_name='Título da Tarefa'),
        ),
    ]
