# Generated by Django 4.2.4 on 2023-09-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criadores', '0001_initial'),
        ('tarefas', '0003_alter_tarefa_options_tarefa_responsavel_tarefa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='responsavel_tarefa',
        ),
        migrations.AddField(
            model_name='tarefa',
            name='responsavel_tarefa',
            field=models.ManyToManyField(blank=True, null=True, to='criadores.criador'),
        ),
    ]
