# Generated by Django 4.2.4 on 2023-08-21 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_alter_livro_ano_lancamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_categoria', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='livro',
            name='categoria_livro',
            field=models.ManyToManyField(to='livros.categoria'),
        ),
    ]
