# Generated by Django 4.2.4 on 2023-08-21 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0003_categoria_livro_categoria_livro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='ano_lancamento',
            field=models.CharField(max_length=4),
        ),
    ]
