# Generated by Django 4.2.4 on 2023-08-23 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0005_livro_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='status',
            field=models.CharField(choices=[(0, 'PUBLISHED'), (1, 'DRAFT'), (2, 'FINISHED'), (3, 'EXPIRED')], default=0, max_length=1),
        ),
    ]
