# Generated by Django 4.2.4 on 2023-08-24 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0007_alter_livro_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='categoria_livro',
        ),
        migrations.AddField(
            model_name='livro',
            name='categoria_livro',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='livros.categoria'),
            preserve_default=False,
        ),
    ]
