# Generated by Django 4.2.4 on 2023-08-24 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0008_remove_livro_categoria_livro_livro_categoria_livro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='categoria_livro',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='livros.categoria'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='status',
            field=models.CharField(blank=True, choices=[('0', 'PUBLISHED'), ('1', 'DRAFT'), ('2', 'FINISHED'), ('3', 'EXPIRED')], default=0, max_length=2, null=True),
        ),
    ]
