# Generated by Django 4.2.4 on 2023-08-24 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0009_alter_livro_categoria_livro_alter_livro_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livro',
            options={'verbose_name': 'Livros do Ramon'},
        ),
    ]
