# Generated by Django 4.2.4 on 2023-08-24 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0010_alter_livro_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livro',
            options={'verbose_name': 'Livro do Ramon', 'verbose_name_plural': 'Livros do Ramon'},
        ),
    ]
