# Generated by Django 4.2.4 on 2023-08-21 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_alter_tarefa_titulo_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
