# Generated by Django 4.2.4 on 2023-08-25 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autor', '0003_autor_delete_celular'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_livro', models.CharField(max_length=200)),
                ('autor_livro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autor.autor')),
            ],
        ),
    ]
