# Generated by Django 4.2.4 on 2023-08-25 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autor', '0003_autor_delete_celular'),
        ('livro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='teste',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='livro',
            name='autor_livro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='autor.autor'),
            preserve_default=False,
        ),
    ]
