# Generated by Django 4.2.4 on 2023-08-25 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0002_livro_teste_alter_livro_autor_livro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='teste',
            field=models.IntegerField(blank=True),
        ),
    ]
