# Generated by Django 4.2.4 on 2023-08-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunos',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
