# Generated by Django 4.2.4 on 2023-08-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0002_alter_alunos_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunos',
            name='peso',
            field=models.DecimalField(decimal_places=5, max_digits=5),
        ),
    ]
