# Generated by Django 4.2.4 on 2023-08-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0004_alter_alunos_peso'),
    ]

    operations = [
        migrations.AddField(
            model_name='alunos',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
