# Generated by Django 4.2.4 on 2023-08-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0005_alunos_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunos',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
