# Generated by Django 4.2.4 on 2023-08-23 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0008_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Academy.professor'),
        ),
    ]
