# Generated by Django 4.2.4 on 2023-08-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0009_curso_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='carga_horaria',
            field=models.TimeField(),
        ),
    ]
