# Generated by Django 4.2.4 on 2023-08-23 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0013_alunos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alunos',
        ),
    ]
