# Generated by Django 4.2.4 on 2023-08-23 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academy', '0016_dadopessoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='alunos',
            field=models.ManyToManyField(to='Academy.aluno'),
        ),
    ]
