# Generated by Django 4.2.4 on 2023-08-23 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0002_alter_autor_data_nascimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='email',
        ),
        migrations.AlterField(
            model_name='autor',
            name='idade',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='autor',
            name='nome',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
