# Generated by Django 4.2.4 on 2023-08-23 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0003_remove_autor_email_alter_autor_idade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='idade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='autor',
            name='nome',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
