# Generated by Django 4.2.4 on 2023-08-23 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0004_alter_autor_idade_alter_autor_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='oi',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
