# Generated by Django 4.2.4 on 2023-08-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0005_autor_oi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='oi',
        ),
        migrations.AddField(
            model_name='autor',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
