# Generated by Django 4.2.4 on 2023-08-24 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0007_perfil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
